export const getSupplies=[
    {
        id:1,
        name:'chocolate',
        min:3,
        avg: 7,
        max:10,
        quantity:4,
        unit:'gr',
        idUnit:1,
    },
    {
        id: 2,
        name: 'pan',
        min: 5,
        avg: 7,
        max: 100,
        quantity: 9,
        unit: 'Pza',
        idUnit:1,
    },
    {
        id: 3,
        name: 'leche',
        min: 3,
        avg: 7,
        max: 10,
        quantity: 1,
        unit: 'L',
        idUnit:1,
    },
    {
        id: 11,
        name: 'chocolate',
        min: 3,
        avg: 7,
        max: 10,
        quantity: 4,
        unit: 'gr',
        idUnit:1,
    },
    {
        id: 12,
        name: 'pan',
        min: 5,
        avg: 7,
        max: 100,
        quantity: 9,
        unit: 'Pza',
        idUnit:1,
    },
    {
        id: 13,
        name: 'leche',
        min: 3,
        avg: 7,
        max: 10,
        quantity: 1,
        unit: 'L',
        idUnit:1,
    },
]